import { test, expect } from '@playwright/test';
import { fixture, externalUrl, encode, choose } from './helpers.mjs';

test('production headers/CSP, local-only network, no persistence or active payload HTML', async ({ page, context, browserName }) => {
  if (browserName === 'chromium') await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  const requests = [], errors = [];
  page.on('request', request => requests.push(request.url()));
  page.on('pageerror', error => errors.push(String(error)));
  page.on('console', message => { if (['error', 'warning'].includes(message.type())) errors.push(message.text()); });
  page.on('requestfailed', request => errors.push(`failed: ${request.url()}`));
  page.on('response', response => { if (response.status() >= 400) errors.push(`HTTP ${response.status()}`); });
  await page.addInitScript(() => { window.cspViolations = []; document.addEventListener('securitypolicyviolation', e => window.cspViolations.push(e.violatedDirective)); });
  const response = await page.goto('/');
  const meta = await page.locator('meta[http-equiv="Content-Security-Policy"]').getAttribute('content');
  expect(response.headers()['content-security-policy']).toBe(`${meta}; frame-ancestors 'none'`);
  expect(response.headers()['x-content-type-options']).toBe('nosniff');
  expect(response.headers()['referrer-policy']).toBe('no-referrer');
  expect(response.headers()['permissions-policy']).toBe('camera=(), microphone=(), geolocation=()');
  await page.waitForLoadState('networkidle'); const initialRequests = [...requests];
  await encode(page, 'https://example.com/?q=%3Cimg%20src=x%20onerror=alert(1)%3E');
  await Promise.all([page.waitForEvent('download'), page.locator('#download-button').click()]);
  await page.locator('#decode-tab').click(); await choose(page, fixture('independent-ascii'));
  await page.locator('#copy-button').click(); await expect(page.locator('#result-hint')).toHaveText('網址已複製。');
  expect(requests).toEqual(initialRequests);
  expect(requests.every(url => new URL(url).origin === 'http://127.0.0.1:4173')).toBe(true);
  expect(await page.locator('a[href^="http"], img').count()).toBe(0);
  expect(await page.evaluate(() => ({ local: localStorage.length, session: sessionStorage.length, cookie: document.cookie, violations: window.cspViolations }))).toEqual({ local: 0, session: 0, cookie: '', violations: [] });
  expect(await context.cookies()).toEqual([]);
  expect(await page.evaluate(() => indexedDB.databases())).toEqual([]);
  expect(await page.evaluate(() => caches.keys())).toEqual([]);
  expect(await page.evaluate(() => navigator.serviceWorker.getRegistrations().then(r => r.length))).toBe(0);
  expect(errors).toEqual([]);
  await page.reload();
  await expect(page.locator('#url-input')).toHaveValue('');
  await expect(page.locator('#download-button')).toBeDisabled();
  await page.locator('#decode-tab').click();
  await expect(page.locator('#decoded-url')).toHaveValue('');
  await expect(page.locator('#copy-button')).toBeDisabled();
});
